### ISSUE TITLE
Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/mongodb-extractor#86]
```
Parsing \"/data/out/tables/***.json\"",
"errorOutput": "[2018-08-29 10:38:54] app-errors.ERROR: Object of class stdClass could not be converted to string {\"class\":\"ErrorException\",\"trace\":\"
#0 [internal function]: {closure}(4096, 'Object of class...', '/code/vendor/ke...', 207, Array)\
#1 /code/vendor/keboola/csvmap/src/Keboola/CsvMap/Mapper.php(207): join(',', Array)\
#2 /code/vendor/keboola/csvmap/src/Keboola/CsvMap/Mapper.php(132): Keboola\\CsvMap\\Mapper->setParentKey(Array, '***...')\
#3 /code/vendor/keboola/csvmap/src/Keboola/CsvMap/Mapper.php(78): Keboola\\CsvMap\\Mapper->parseRow(Object(stdClass), Array)\
#4 /code/src/Keboola/MongoDbExtractor/Parser/Mapping.php(50): Keboola\\CsvMap\\Mapper->parse(Array)\
#5 /code/src/Keboola/MongoDbExtractor/Export.php(94): Keboola\\MongoDbExtractor\\Parser\\Mapping->parse(Array)\
#6 /code/src/Keboola/MongoDbExtractor/Extractor.php(110): Keboola\\MongoDbExtractor\\Export->parseAndCreateManifest()\
#7 /code/src/Keboola/MongoDbExtractor/Application.php(36): Keboola\\MongoDbExtractor\\Extractor->extract('/data/out/table...')\
#8 /code/src/run.php(48): Keboola\\MongoDbExtractor\\Application->actionRun('/data/out/table...')\
#9 {main}\"} 
```

**Comment by ondrejhlavacek** [comment]
https://connection.keboola.com/admin/utils/logs?file=2018/08/29/12/2018-08-29-12-30-28-5b8675c4e6df8-exception

**Comment by ujovlado** [comment]
Toto vyzera na vadny mapping alebo problem s parsovanim. Skoda, ze z tej csvmap chyby to nie je vidno. Skusim to nejako nasimulovat. Tie joby totiz popadali hned.

**Comment by ujovlado** [comment]
Issue na CsvMap: https://github.com/keboola/php-csvmap/issues/7
