### ISSUE TITLE
Failed to parse MongoDB URI: 'mongodb://...'

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/mongodb-extractor#90]
Na první pohled nevidím, co je na tý url blbě
```
#0 /code/src/Keboola/MongoDbExtractor/Extractor.php(77): MongoDB\\Driver\\Manager->__construct('mongodb://user:...')
#1 /code/src/Keboola/MongoDbExtractor/Extractor.php(59): Keboola\\MongoDbExtractor\\Extractor->createConnection(Array)
#2 /code/src/Keboola/MongoDbExtractor/Application.php(48): Keboola\\MongoDbExtractor\\Extractor->__construct(Array)
#3 /code/src/run.php(46): Keboola\\MongoDbExtractor\\Application->actionTestConnection()
#4 {main}
```

https://connection.keboola.com/admin/utils/logs?file=2019/03/22/15/2019-03-22-15-00-14-5c94ea6e266e9-exception
https://connection.keboola.com/admin/utils/logs?file=2019/03/22/15/2019-03-22-15-00-14-5c94ea6e3130e-log

**Comment by ujovlado** [comment]
Pozrem sa, podobnu vec som ale fixoval https://github.com/keboola/mongodb-extractor/pull/72

**Comment by ujovlado** [comment]
Aha, oni maju v hoste `http`

**Comment by ujovlado** [comment]
Tak to staci skoncertovat na user err, poriesim

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1554416287007800
